---
# tasks file for copy
- name: copying file
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
     - { src: 'test2.txt', dest: '/home/ec2-user' }
     - { src: 'test1.txt', dest: '/home/ec2-user' }
  when: ansible_os_family == "RedHat"
  tags:
    - COPY

- name: create a file
  command: touch /home/ec2-user/demo.txt
  become: yes
  become_user: root
  tags: 
    - create 
