version: "3"
services:
  nginx:
    image: febdevops/rocks:nginx
    ports:
      - 443:80
    networks:
      - frontend
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120
      placement:
        constraints: [node.role == manager]
    environment:
      - appname = Devops

networks:
  frontend:

volumes:
  db-data:
