---

- hosts: devops
  vars:
    list1: ['Template iterate','Template loop','Template item']
  tasks:
    - name: Ansible template loop example.
      template:
        src: templates.j2
        dest: /home/ec2-user/output.txt
        mode: 0777

